name: line_follower_pro_max
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: 12.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.jpeg
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/app_icon.jpeg
  web:
    generate: true
    image_path: assets/icons/app_icon.jpeg
  windows:
    generate: true
    image_path: assets/icons/app_icon.jpeg
  macos:
    generate: true
    image_path: assets/icons/app_icon.jpeg

flutter:
  uses-material-design: true
